### ISSUE TITLE
Unable to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by ychen404** [Open-TEE/project#25]
Hi,

I am not able to build the source following the instructions on the website: 
http://open-tee.github.io/documentation/
The following is the error that I am getting: 

linking opentee-engine
ERROR: /usr/bin/gcc -g -O0 -Wall -Wextra -m64 -pipe -fvisibility=default -Wpointer-arith -I/usr/local/include -fPIC -DOT_LOGGING -D_FORTIFY_SOURCE=2 -I/home/local/ASUAD/ychen404/Open-TEE/emulator/include -o /home/local/ASUAD/ychen404/Op
en-TEE/debug/InternalApi.0d64191a/3a52ce780950d4d9/openssl_1_0_2_beta_rsa_oaep.c.o -c /home/local/ASUAD/ychen404/Open-TEE/emulator/internal_api/openssl_1_0_2_beta_rsa_oaep.c

ERROR: /home/local/ASUAD/ychen404/Open-TEE/emulator/internal_api/openssl_1_0_2_beta_rsa_oaep.c: In function ‘beta_PKCS1_MGF1’:
/home/local/ASUAD/ychen404/Open-TEE/emulator/internal_api/openssl_1_0_2_beta_rsa_oaep.c:39:13: error: storage size of ‘c’ isn’t known
  EVP_MD_CTX c;
             ^
/home/local/ASUAD/ychen404/Open-TEE/emulator/internal_api/openssl_1_0_2_beta_rsa_oaep.c:74:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]
  EVP_MD_CTX_cleanup(&c);
  ^~~~~~~~~~~~~~~~~~
  EVP_MD_CTX_create
/home/local/ASUAD/ychen404/Open-TEE/emulator/internal_api/openssl_1_0_2_beta_rsa_oaep.c:39:13: warning: unused variable ‘c’ [-Wunused-variable]
  EVP_MD_CTX c;
             ^
ERROR: Process failed with exit code 1.

It seems that the problem comes from EVP_MD_CTX. 
After googling, I found out EVP_MD_CTX is related to openssl. 
But I've no idea which version of openssl should I use, after updating to the latest one (1.1.1f), I am still facing the same problem. Should I downgrade my openssl to a specific version? Or I am running into some other issue?

Following is the version of my openssl. 
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020

Any help is appreciated!

**Comment by TanelDettenborn** [comment]
Hi ychen404,

Unfortunately OpenTEE is not migrated to use the latest versions of OpenSSL. OpenTEE requires OpenSSL version 1.0.x.

> Or I am running into some other issue?

I would suggest to use a VM (run 16.04 with older OpenSSL version), because of OpenSSL downgrade from 1.1.x to 1.0.x *might* cause stability issues in the system! But OpenTEE *should* compile and run without problems on 16.04 with 1.0.x :)

**Comment by ychen404** [comment]
Hi,
Thanks for getting back to me so quickly.
I downgraded OpenSSL from 1.1.1f to 1.0.2u, but I’m still getting the same
error message.
Did I miss something?

Thanks.

**Comment by TanelDettenborn** [comment]
I have troubles to reproduce the issue. I am able to reproduce above compiling error with OpenSSL 1.1.1, but not with 1.0.2. I have downloaded OpenSSL 1.0.2 sources from their Github repository, compiled it and then build OpenTEE against it without any errors. Also build OpenTEE runs without issues.

Therefore I am suspecting that you are still building against OpenSSL 1.1.1 (specially if you are facing exactly same error).

**Comment by ychen404** [comment]
Hi Tanel,

Thanks for your response!
I did compile from the source using OpenSSL 1.0.2u.
I will try again with a new virtual machine.
Thanks.

Best,
Yitao

**Comment by dssu** [comment]
> I have troubles to reproduce the issue. I am able to reproduce above compiling error with OpenSSL 1.1.1, but not with 1.0.2. I have downloaded OpenSSL 1.0.2 sources from their Github repository, compiled it and then build OpenTEE against it without any errors. Also build OpenTEE runs without issues.
> 
> Therefore I am suspecting that you are still building against OpenSSL 1.1.1 (specially if you are facing exactly same error).

Hello, I am facing this same issue and have been trying to figure out how to use the 1.0.2 sources with the build system. Could you let me know how you did this or any tips? Thanks
